# Generated by Django 4.2.8 on 2023-12-14 14:51

import uuid

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                ("version_id", models.UUIDField(editable=False)),
                (
                    "version",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("version_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
